name: deploy

on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed

jobs:
  run_deploy:
    name: run deploy
    runs-on: ubuntu-latest

    steps:
      - name: install ssh keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
      - name: connect, pull and restart container
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout master && git pull && docker compose up -d --build frontend && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
